import React, { useEffect, useState } from 'react';
import { ArrowRight, Loader2 } from 'lucide-react';

type ContentType = 'blog' | 'news';
type Item = { _id: string; type: ContentType; title: string; slug: string; excerpt?: string; featuredImage?: string; altText?: string; category?: string; publishDate?: string | null; tags?: string[]; };

export default function ContentListingPage({ type }: { type: ContentType }) {
  const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const isNews = type === 'news'; const title = isNews ? 'Salon News' : 'Beauty Journal'; const subtitle = isNews ? 'The latest updates, announcements and stories from Layali Al Zahra Beauty Lounge.' : 'Beauty, hair and salon advice created for life in Dubai and the UAE.';
  useEffect(() => { let active = true; fetch(`/api/content?type=${type}&limit=50`).then(async r => { const d = await r.json().catch(() => ({})); if (!r.ok || !d.success) throw new Error('Unable to load content'); return d; }).then(d => { if (active) setItems(d.items || []); }).catch(() => { if (active) setError('Content is temporarily unavailable.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [type]);
  return <div className="min-h-screen bg-gradient-to-br from-rose-50 via-pink-50 to-rose-100 py-12 pb-20"><div className="container mx-auto px-4"><div className="mb-14 text-center"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-rose-700">Layali Al Zahra</p><h1 className="mt-3 font-tangerine text-6xl text-rose-900 md:text-8xl">{title}</h1><p className="mx-auto mt-3 max-w-3xl text-lg text-gray-700">{subtitle}</p></div>{loading ? <div className="flex justify-center py-16"><Loader2 className="h-8 w-8 animate-spin text-rose-700" /></div> : error ? <div className="mx-auto max-w-2xl rounded-lg bg-white p-8 text-center shadow-lg"><p className="font-medium text-rose-900">{error}</p><p className="mt-2 text-sm text-gray-600">Please try again shortly.</p></div> : items.length === 0 ? <div className="mx-auto max-w-2xl rounded-lg bg-white p-8 text-center shadow-lg"><p className="font-medium text-rose-900">No {isNews ? 'news' : 'articles'} are published yet.</p><p className="mt-2 text-sm text-gray-600">New content will appear here as soon as it is published.</p></div> : <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{items.map(item => <article key={item._id} className="overflow-hidden rounded-lg bg-white shadow-lg transition-shadow hover:shadow-2xl"><a href={`#${type}/${item.slug}`} className="block"><div className="h-60 overflow-hidden bg-rose-100">{item.featuredImage ? <img src={item.featuredImage} alt={item.altText || item.title} className="h-full w-full object-cover transition-transform duration-300 hover:scale-105" /> : <div className="flex h-full items-center justify-center text-rose-700">Layali Al Zahra</div>}</div><div className="p-6"><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-rose-50 px-2.5 py-1 font-medium text-rose-800">{item.category || (isNews ? 'News' : 'Beauty')}</span>{item.publishDate && <span className="text-gray-500">{new Date(item.publishDate).toLocaleDateString()}</span>}</div><h2 className="mt-3 text-xl font-semibold text-rose-900">{item.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-gray-600">{item.excerpt || ''}</p><span className="mt-5 inline-flex items-center text-sm font-medium text-rose-800">Read more <ArrowRight className="ml-2 h-4 w-4" /></span></div></a></article>)}</div>}</div></div>;
}
